Repository BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq, pull requests merged in 2021-05, with the labels that each got.

#30 linked relevant issue ids to IET-HF.md
  IET-HF.md
Labels: documentation

#32 created skeleton .md files for documenting the identified scope of th…
  docs/build-framework.md
  docs/code-analysis.md
  docs/deployment-assistance.md
  docs/exploratory-testing.md
  docs/non-functional-attributes.md
Labels: documentation

#34 Sonarqube in lib project
  .github/workflows/sonarqube.yml
  lib/build.gradle
Labels: technology focus

#40 Fixed sonarqube some problems
  .gitignore
  lib/src/main/java/tr/com/srdc/ontmalizer/XML2OWLMapper.java
  lib/src/main/java/tr/com/srdc/ontmalizer/XSD2OWLMapper.java
  lib/src/main/java/tr/com/srdc/ontmalizer/helper/XSDUtil.java
Labels: clean up

#42 Add more things to munkanaplo.tex
  docs/munkanaplo.tex
Labels: Management, documentation

#41 Code analysis documentation
  .gitignore
  .idea/.name
  .idea/gradle.xml
  .idea/libraries-with-intellij-classes.xml
  docs/code-analysis.md
  docs/imgs/sonarqube1.png
  docs/imgs/sonarqube2.png
Labels: documentation
